### ISSUE TITLE
Feature request: Setting different zoom levels for mobile/tablet viewport

### ISSUE THREAD

**Issue by voneff** [flopperj/osm-map-elementor#11]
Hi there,

thank you once again for your work in this plugin – I think you broke the world speed record for implementing new features! ;-)

I have another idea: On my map, the markers are fairly spread out and I selected a zoom level that shows the markers nicely on desktop. On mobile though, only a middle group of markers are shown, and markers further left and right are out of sight.

A solution could be to set a different zoom level for mobile and table. 
Or, the widget could "automatically" adjust the map width according to marker spread and screen width.

Just a thought, looking forward to further working with your plugin!

Cheers

Alex

**Comment by flopperj** [comment]
Hi Alex,

This is a wonderful idea.  I definitely do see a need for this and will work on implementing it on the next update release :)

**Comment by flopperj** [comment]
@voneff - I just added this functionality. It's currently on the dev branch if you want to test it out:
[https://github.com/flopperj/osm-map-elementor/tree/james/dev](https://github.com/flopperj/osm-map-elementor/tree/james/dev)

**Comment by flopperj** [comment]
@voneff - Pushed the latest update for the plugin. Thanks again for your feedback. I appreciate it.
