### ISSUE TITLE
Open button link in self

### ISSUE THREAD

**Issue by AJC31** [flopperj/osm-map-elementor#13]
Hello,

I just installed OSM Map Widget for Elementor and think it's a great addon.
However I would like to open the button link in self and not in blanck, could you help me.
Thank you

**Comment by flopperj** [comment]
Thank you for raising this issue. Will look at addressing it on the next plugin update.

**Comment by flopperj** [comment]
@AJC31 I'm closing this issue. I've merged this [pull request](https://github.com/flopperj/osm-map-elementor/pull/16) that addresses the button links target. Thank you for your suggestion.
