### ISSUE TITLE
Not visible

### ISSUE THREAD

**Issue by yupman85** [flopperj/osm-map-elementor#14]
Map is visible and working properly inside of Elementor, but when published and viewing on any browser, the map is not visible.  Any assistance is appreciated!

**Comment by flopperj** [comment]
@yupman85 - Sorry for the long wait in response. A few questions, what version of the plugin are you currently using? Are there any errors when you view your browser's console?

**Comment by BananaAcid** [comment]
We have the same Problem here, using v1.0.11 on Elementor Pro v3.5.2 (as well as Elementor Pro v3.3.6) - no JS errors.

There seem to be no "show debugging infos" option.

HTML result is :

![image](https://user-images.githubusercontent.com/1894723/145821754-759f25e6-d9dd-42c8-ab0c-9f1912dd861d.png)

**Comment by QuoterMusic** [comment]
@HiceoTristan @BananaAcid @yupman85 
I have done an update which will soon be online at wordpress.org in which all the deprecated code I could find has been fixed.
As well as a few other tweaks, feel free to try the update once it's online and let me know if your problem still exists.
