### ISSUE TITLE
E_PARSE error line 1269 of osm-map-elementor/osm-map.php

### ISSUE THREAD

**Issue by kab29** [flopperj/osm-map-elementor#15]
Hi,

Activating the plugin creates an error on my site :
E_PARSE error line 1269 of wp-content/plugins/osm-map-elementor/osm-map.php. 
Message : syntax error, unexpected token "\", expecting "]"

Thanks for any solution.

WordPress version 5.7.2
Template : Hoteller
OSM Map Widget for Elementor (version 1.0.7)
PHP version 8.0.2

**Comment by kab29** [comment]
Line 1269 : Deleting the useless space before Controls_Manager solved the pb : 
                'type' => \Elementor\ Controls_Manager::COLOR,

**Comment by flopperj** [comment]
@kab29 - Thank you so much for pointing this out. I'll update the repo with the bugfix suggestion.
