### ISSUE TITLE
Deprecated: Elementor\Scheme_Typography ist seit Version 2.8.0 

### ISSUE THREAD

**Issue by linuxlurak** [flopperj/osm-map-elementor#17]
I get this notice: 
`Deprecated: Elementor\Scheme_Typography ist seit Version 2.8.0 veraltet! Benutzen Sie stattdessen Elementor\Core\Schemes\Typography. in /var/www/layer8/wordpress/wp-includes/functions.php on line 5051`

I guess it's relating to this line of your code:
https://github.com/flopperj/osm-map-elementor/search?q=Elementor%5CScheme_Typography

**Comment by flopperj** [comment]
@linuxlurak - Thank you for raising this issue. I've started cleaning up deprecated calls/references. When you have a chance could you please download the plugin from my [dev branch](https://github.com/flopperj/osm-map-elementor/tree/james/dev) to see if that fixes the issue. Once I clean up everything I'll promote my latest changes to wordpress.

**Comment by linuxlurak** [comment]
As far as I could check your revision, it seems to work fine. Thank you very much!
