### ISSUE TITLE
Specialised Tiles

### ISSUE THREAD

**Issue by Ephesian** [flopperj/osm-map-elementor#19]
Hello

I would like to use specialised tiles that are available from the Ordnance Survey in the UK.  Would it be possible ? The formats are 

ESRI Shapefile, 
GML 3, 
GeoPackackage
MapInfo TAB
Vector Tiles (MBTiles)

https://osdatahub.os.uk/downloads/open. -> https://osdatahub.os.uk/downloads/open/BoundaryLine

**Comment by flopperj** [comment]
@Ephesian I'm really not sure. Would you mind taking a stub at it and submitting a PR? I use [LeafletJS](https://leafletjs.com/reference-1.7.1.html#tilelayer) which has the ability to add custom tiles.

**Comment by Ephesian** [comment]
Hi James,

 

I’ll have a look this week, if I can get my Mapserver working properly.

 

If I need help with your plugin I’ll shout

 

Graham

 

From: James Arama ***@***.***>
Reply to: flopperj/osm-map-elementor ***@***.***>
Date: Friday, 1 October 2021 at 18:28
To: flopperj/osm-map-elementor ***@***.***>
Cc: Graham Redfern ***@***.***>, Mention ***@***.***>
Subject: Re: [flopperj/osm-map-elementor] Specialised Tiles (#19)

 

@Ephesian I'm really not sure. Would you mind taking a stub at it and submitting a PR? I use LeafletJS which has the ability to add custom tiles.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by QuoterMusic** [comment]
@Ephesian 
I have add Custom Tile URL Support in Version 1.0.10
You can if your map server is running correctly simply add the URL in the plugin settings under Custom Map Tile URL.
best wishes
Quoter

**Comment by flopperj** [comment]
Thank you for handling this @QuoterMusic
