### ISSUE TITLE
Text formatting for marker content

### ISSUE THREAD

**Issue by Currrupted** [flopperj/osm-map-elementor#2]

**Comment by flopperj** [comment]
@Currrupted - Do you have any particular feedback as to what type of text formatting you're looking to add on the marker contents?

**Comment by Currrupted** [comment]
> @Currrupted - Do you have any particular feedback as to what type of text formatting you're looking to add on the marker contents?

Thank you for your response. Unfortunately, I forgot to provide a description to my issue.

Personally, I think it would be great to have the possibility to provide basic text formatting, as usually provided by Elementor. So what I was imagining is:

- ability to set character style to Bold, Italic, Strikethrough or Underlined
- option to add hyperlinks
- automatically generate hyperlinks for websites, e-mail addresses (mailto: links) and 

To be honest, I don't know if these suggestions are actually practical, it's just that I expected this to work similarly to the default Wordpress formatting. Thank you for your time and effort.

**Comment by flopperj** [comment]
@Currrupted - Have you had the chance to play around with the typography controls under the styles tab? The marker description text field can also take raw html if you want to add hyperlinks. Below is a screenshot of what I'm referring to.

![marker_content_text_formatting](https://user-images.githubusercontent.com/1606264/100054361-b94cc700-2dd6-11eb-8e77-5cc137401029.jpg)
