### ISSUE TITLE
Custom OSM Servers in the Settings

### ISSUE THREAD

**Issue by QuoterMusic** [flopperj/osm-map-elementor#20]
It would be great if you could set your own map server URL in the settings.

I use a self-hosted version of OSM due to privacy issues

I have customized the URL directly in the plugin for me but it would be nice to be able to do that directly via the settings.

<?php if(empty($settings['geoapify_tile']) || $settings['geoapify_tile'] == 'osm-carto'): ?>
                L.tileLayer('https://MY-URL/tile/{z}/{x}/{y}.png', {
                    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
                    maxZoom: 18
                }).addTo(map);
                <?php else: ?>

**Comment by flopperj** [comment]
Thank you for your feedback. At the moment, I don't have any spare cycles to contribute much. Would you be able to take a stub at this and submit a PR of your implementation? Will circle back when I'm able to.

Thanks,

**Comment by QuoterMusic** [comment]
#21 
Adding Custom Map Tile URL Support

I've taken a look and added the function for Custom Map Tile URLs.
Additionally I have added Additional Attribution for Custom Maps
It's the first time I worked on a wordpress plugin I hope it all fits like this
