### ISSUE TITLE
Everything just... disappeared?

### ISSUE THREAD

**Issue by coulsobr** [flopperj/osm-map-elementor#29]
Hello, I updated my website to the newest Elementor and Elementor Pro version and when I went to add the map into a page I couldn't seem to find the block in my options. I went and checked a different page that had the map already set up and working fine and it was just gone. The plugin itself is still activated so I think there might be a compatibility issue with the new update? Luckily I backed up my website so I didn't lose all the pins I put into the previously set up map.

Elementor version: 3.17.0-cloud1
Elementor Pro version: 3.16.0-cloud2

**Comment by QuoterMusic** [comment]
Hello coulsobr,

it is probably a compatibility problem due to the Elementor deprecations.

I will update the plugin the next days and then everything should work again.

Best regards
Niklas/Quoter

**Comment by QuoterMusic** [comment]
@coulsobr 
I have done an update which will soon be online at wordpress.org in which all the deprecated code I could find has been fixed.
As well as a few other tweaks, feel free to try the update once it's online and let me know if your problem still exists.
