### ISSUE TITLE
[Bug] Map widget not visible on some devices

### ISSUE THREAD

**Issue by Currrupted** [flopperj/osm-map-elementor#3]
**Bug description:**

The map is not visible on my webpage, but only on some devices/networks.

**Expected behaviour:**

When opening a wordpress webpage that uses the Elementor OSM Plugin, that plugin should render a map according to the settings of the site.

**What actually happens:**

The area where the map should appear remains blank. The problem persists after both reloading the website and restarting the device.

However, I know from other people, who are involved too, that the widget works for them. Also, when I edit the contents of the page in Elementor, the map will display perfectly fine.

**System specifications:**

Wordpress: Wordpress 5.5.3
Elementor: Elementor Pro v3.0.6
Browser: Mozilla Firefox (83.0); Chromium (87.0.4280.66)
System: Kubuntu 20.10 (Kernel version: 5.8.0-29-generic)
Memory: 8 GB DDR3 RAM

**Comment by flopperj** [comment]
@Currrupted - Thank you for reporting this. When you look in your browser’s console, using inspector tools, are there any visible JavaScript errors pertaining the map widget?

**Comment by Currrupted** [comment]
> @Currrupted - Thank you for reporting this. When you look in your browser’s console, using inspector tools, are there any visible JavaScript errors pertaining the map widget?

Thank you for your reply! I tried collecting error messages for JavaScript. On Firefox 83.0, I get the following error when trying to access the page that has the OSM widget integrated:

```js
Uncaught ReferenceError: jQuery is not defined
    <anonymous> XXXmywebpage.org/:222
```

However, I am not sure if this is the correct error message. I get this only when trying to access the map widget.

---

This is what I get in Chromium:

```js
Uncaught ReferenceError: jQuery is not defined
    at (index):222
```

**Comment by flopperj** [comment]
@Currrupted - The latest plugin update should address this issue. Feel free to re-open this ticket if you're still having issues.

**Comment by sunnyvgn** [comment]
Hey, the OSM Maps online works while I'm logged on to wordpress. It doesn't seem to work on any device. Do you have the same problem?

**Comment by flopperj** [comment]
@sunnyvgn - What plugin version are you on? And are there any errors you're seeing in your browser's console while logged out?

**Comment by sunnyvgn** [comment]
Version 1.0.6. No errors while I'm logged out. The part where the map should be is just blank/empty.

**Comment by sunnyvgn** [comment]
@flopperj do you have an solution for this problem? I checked it on multiple devices everybody has the same problem.

**Comment by flopperj** [comment]
@sunnyvgn - One last thing to try weed out any conflicts, could you please deactivate all plugins to see if it's conflict with another plugins on your site? Let me know if you notice any difference.

**Comment by sunnyvgn** [comment]
@flopperj just deactivated the all plugins except elementor and elementor pro (just two aditional plugins). Same. Just blank. I don't see any difference.

**Comment by flopperj** [comment]
@sunnyvgn I've re-opened this issue. I'm still working on other bugfixes and features. I have the latest updates on the [dev branch](https://github.com/flopperj/osm-map-elementor/tree/james/dev). Could you download the latest zipped plugin from there to see if you're still seeing the same issue.

**Comment by sunnyvgn** [comment]
@flopperj nice it's working :-)

**Comment by flopperj** [comment]
@sunnyvgn awesome!
