### ISSUE TITLE
Stamen Style URLs are Updating October 31st, 2023

### ISSUE THREAD

**Issue by pushing-boulders** [flopperj/osm-map-elementor#31]
Good day @flopperj.  I am working with someone who is using the Stamen map tiles and noticed that you are using outdated fastly URLs in this project.  I'll create a quick pull request to address the issue.

More details about this change at Stamen here:  https://stadiamaps.com/stamen/

A question for you:  Do you know if your plugin can handle retina (2x) tiles?

**Comment by pushing-boulders** [comment]
Here is the pull request:  https://github.com/flopperj/osm-map-elementor/pull/32

I think I did everything correctly, but apologize if I messed something up.  I am fairly new to contributing on GitHub.

**Comment by flopperj** [comment]
Hi @pushing-boulders,
I'm not 100% sure, but will take a look at your PR some time today. 
Thank you for your contributions :)

**Comment by QuoterMusic** [comment]
@pushing-boulders @flopperj 
I am in the process of reworking the plugin since many seem to have problems since the last Elementor deprecations. 
I'll take a look at the whole thing with the map tiles. 
Since I had built in these maps to be able to offer maps without API.

**Comment by pushing-boulders** [comment]
Thanks @QuoterMusic and @flopperj.  

Understood.  I was looking at the main page for the plugin, but didn't see how to add a custom URL.  The code looks like it supports this?

                <?php elseif( $settings['geoapify_tile'] == 'custom-tile'):?>
                L.tileLayer('<?php echo !empty($global_settings['osm_custom']) ? esc_textarea(__($global_settings['osm_custom'], self::$slug)) : null; ?>', {
                    attribution: '<a href="<?php echo !empty($global_settings['osm_custom_attribution_url']) ? esc_textarea(__($global_settings['osm_custom_attribution_url'], self::$slug)) : null; ?>" target="_blank"><?php echo !empty($global_settings['osm_custom_attribution']) ? esc_textarea(__($global_settings['osm_custom_attribution'], self::$slug)) : null; ?></a> | © OpenStreetMap <a href="https://www.openstreetmap.org/copyright" target="_blank">contributors</a>',
                    maxZoom: 18
                }).addTo(map);
                
I don't Elementor, so I cannot try on my side, but this this an option?  To add your own XYZ source?

To be clear, the tiles are still support, free of use, but you do need to setup an account and then add your domain for domain authentication.

**Comment by QuoterMusic** [comment]
@pushing-boulders 

Yes the plugin has a possibility to use own map tiles the code for it is stored in the osm-map-elementor.php.

The part you sent is the selection in the Elementor plugin.

The own Map Tiles URL can be made in the settings.

/wp-admin/options-general.php?page=osm-map-elementor

I'll take a look at your changes right now. And give you feedback in the next few hours.

Unfortunately not quite as I understood since there is now a limit on the calls and a commercial use is no longer allowed.

**Comment by pushing-boulders** [comment]
@QuoterMusic 

Thank you for the follow-up and URL for adding your own.  I will share this with the user to see if they can also proceed with that route.

To be clear, the usage for Stadia Maps is as follows:

1. Local development does not require an API key or authentication.  Requests will be treated as if they are coming from the free plan.
2. There is a free tier that includes 200,000 credits (1 tile = 1 credit) per month.  You cannot use this tier for commercial use.
3. Commercial use is allowed on any of the paid tiers, which start at $20 USD for 1M credits per month.

I understand if you do not want to include them in the project due to these changes.

**Comment by QuoterMusic** [comment]
@pushing-boulders 

We're in the process of integrating your changes, but I'll prepare a few more changes afterwards and then we'll release it in an update as version 1.2. 

No, I don't mind, I'll also add the other new maps today. I just think it's something  It's sad that the company is taking this step.

**Comment by pushing-boulders** [comment]
Thanks @QuoterMusic.  Sounds good.

I know the change for Stamen included financial considerations:

> Unfortunately, running this free tiling service costs money, upwards of $100,000 - $200,000 a year, too much for the operating budget of a small agency that is fundamentally not in the business of serving tiles. Since Stamen is not a nonprofit, we don't qualify for grants that would allow us to keep maintaining this service in the public interest, and since serving tiles is not our core business, we haven't had the resources to maintain it the way we would like. The maps you have been getting from our tile servers are incomplete and out of date. The maps we are migrating our services to are current, complete, performant, and well supported. 

From https://maps.stamen.com/stadia-partnership/
