### ISSUE TITLE
Map not show in front-end, but show well on back-end while edit page

### ISSUE THREAD

**Issue by mmorenosaiz** [flopperj/osm-map-elementor#39]
After update to Wordpress 6.4.3, Elementor 3.20.2 and Elementor Pro 3.20.1 OSM not show maps as you can see at https://www.monegas.com/contacto/ or https://www.monegas.com. I use OSM Map widget for elementor 1.2.1.
I have disabled all Elementor performance options, uninstalled Autoptimizer plugin but nothing has worked. If I modify the map, it shows once correctly and when I reload the page, it doesn't show the map again. Or it doesn't show it at all.
No errors in javascript.
¿Can you help me please?

**Comment by AndyTheFactory** [comment]
Hi @mmorenosaiz 

i had the same problem, i removed the "!" from line 
https://github.com/flopperj/osm-map-elementor/blob/02309059c5db8de5481644469c901d6b3ab6a442/osm-map.php#L1970C1-L1971C1

making it :

```                   `
                   if ($in_footer) {
                        add_action('wp_print_footer_scripts', $cb_maybe, 11);
                    } else {
                        // Dependencies were not included in `wp_head` or `wp_footer`.
                    }
```

Not sure if it breaks something else, did not manage to test it very thorough

But as far as i can see, it includes the dependencies once and there are no js errors

**Comment by QuoterMusic** [comment]
As far as I could see everything looks fine with the change and works again thanks for the solution. I'll post an update shortly.

**Comment by QuoterMusic** [comment]
As far as I could see everything looks fine with the change and works again thanks for the solution. I'll post an update shortly.
