### ISSUE TITLE
[Bug] Editing large number of map markers overloads system, sometimes causing browser to crash

### ISSUE THREAD

**Issue by Currrupted** [flopperj/osm-map-elementor#5]
**Bug description**

I am having some problems when I edit the contents of the map. I usually see a drop in performance and sometimes my browser also crashes. This happens only when editing the map markers, specifically when entering longer texts or HTML elements in the map marker contents. 

**Expected behaviour:**

When selecting the map widget and entering data in the contents of the map marker, the markers displayed should update normally without any performance issues or crashes. Entering text in the map marker contents should work similarly to the default text editing in Elementor.

**Actual behaviour:**

When trying edit the given map markers, the webpage slows down. This leads to lagging or sometimes even crashes the browser that is being used. When changing too many properties or entering too much text, I have to wait for the systems to finish, which can take up to several minutes. Occasionally I have to kill the program to take back control.

Interestingly, this works better in Chromium, which seems to handle the load much more efficiently. I tried to record a benchmark for this use case, however I cannot upload images here, unfortunately.

**System information:**

Plugin version installed: 1.0.4
Browser: Firefox 83.0 and Chromium
Memory: 8 GB DDR RAM
Operating System: Kubuntu 20.10

**Comment by flopperj** [comment]
@Currrupted - Thanks for reporting this. How many markers are you working with so that I try to recreate on my end?

**Comment by Currrupted** [comment]
> @Currrupted - Thanks for reporting this. How many markers are you working with so that I try to recreate on my end?

Thank you for your reply. We are working with **15** markers in total, with their own marker content each.

If needed, I can try uploading screenshots of the benchmark results.

**Comment by flopperj** [comment]
@Currrupted - The screenshot of the benchmark results would be really useful with trying to fix the issue.

**Comment by Currrupted** [comment]
> @Currrupted - The screenshot of the benchmark results would be really useful with trying to fix the issue.

Hey! Sorry for the delays.  Here are the results for the benchmark:

Overview/general
![OVERVIEW_NetworkPerformace_OSMWidget_BugReport](https://user-images.githubusercontent.com/13292623/102256260-77adc880-3f0b-11eb-8295-b70001a5ddd7.png)

Main:
![MAIN_NetworkPerformace_OSMWidget_BugReport](https://user-images.githubusercontent.com/13292623/102256273-7aa8b900-3f0b-11eb-8840-5ac94c540e28.png)

Memory Usage:
![MEMORY_NetworkPerformance_OSMWidget_BugReport](https://user-images.githubusercontent.com/13292623/102256294-81cfc700-3f0b-11eb-9b39-05f5828b02bd.png)

**Comment by flopperj** [comment]
@Currrupted - is this still an issue in latest update?

**Comment by flopperj** [comment]
@Currrupted - Going to close this. Feel free to reopen if still having problems with latest updated plugin.
