### ISSUE TITLE
[bug] Accent in description and js error

### ISSUE THREAD

**Issue by Prozac2000** [flopperj/osm-map-elementor#7]
Using accent in description causes javascript error. Workaround is replace accent (') with acute accent (´).

### Solution:
escape accent in description with (\') in js code.

![works](https://user-images.githubusercontent.com/14149828/107943674-53af4780-6f8d-11eb-8bee-6024daba168b.jpg)
![bug](https://user-images.githubusercontent.com/14149828/107943675-5447de00-6f8d-11eb-9ef3-d4e51df84de0.jpg)

**Comment by flopperj** [comment]
@Prozac2000 - Thank you so much for reporting this. Will be working on adding a fix to this on the next update.
