### ISSUE TITLE
Feature request: Add setting for disabling zoom on scroll and other zoom controls

### ISSUE THREAD

**Issue by voneff** [flopperj/osm-map-elementor#8]
Hi there, thank you very much for your work on this plugin! Works really great.

I would like to propose a feature idea: It would be really great if there was a setting within the Elementor widget panel that disables the map zoom on scroll.  Even better: an additional setting to disable all zoom controls

Cheers!

**Comment by flopperj** [comment]
@voneff - Thank you for this suggestion. It's a great idea. I will work on incorporating it to the next update.

**Comment by voneff** [comment]
@flopperj - You're welcome! Looking forward to his.
