### ISSUE TITLE
Feature request: Setting for disabling popup windows

### ISSUE THREAD

**Issue by voneff** [flopperj/osm-map-elementor#9]
Hi there,

another feature idea: 

If I add multiple markers to my map, I would like to add a title to be able to differentiate between them.
Adding a title though triggers that website visitors can open a popup that shows the title when clicking on the markers.

If I do not want to show popups on my map, I have to remove the title – but that makes it impossible to differentiate between the markers in the Elementor admin panel.

I can easily hide the `.leaflet-popup` class in my CSS – but there could be a better way to organize markers or turning off popups as a setting.

Thank you and cheers!

**Comment by flopperj** [comment]
@voneff - Great feature idea. Will be integrating this on next update.

**Comment by voneff** [comment]
@flopperj - Great, thanks for picking this up! Cheers!
